# Flight related queries
GET_FLIGHTS = "SELECT * FROM IEPLANE.FLIGHTS FETCH FIRST 100 ROWS ONLY"

# Plane related queries
GET_AIRPLANES = "SELECT * FROM IEPLANE.AIRPLANES"

# Ticket related queries
GET_TICKETS = "SELECT * FROM IEMASTER.TICKETS FETCH FIRST 100 ROWS ONLY"
